version: '2'
services:
  rollout:
    image: ditchitall/rollout:latest
    build: .
    entrypoint: python rollout
    environment:
      - DOCKERCLOUD_NAMESPACE=medianeut
    volumes:
      - ./src:/data/src
      - ~/.docker/config.json:/root/.docker/config.json
